# Generated by Django 2.0 on 2018-09-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180921_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='minimum_days_of_deposit_to_take_loan',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemuser',
            name='current_amount_in_account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='current_loan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='loan_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='loan_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='loan_next_refund_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
