# Generated by Django 2.0 on 2018-09-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180921_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=20)),
                ('used_payment_method', models.CharField(max_length=20)),
                ('transacted_amount', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
                ('transaction_verified_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('transaction_carried_out_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_verified_by', to='main_app.SystemUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_of_user', to='main_app.SystemUser')),
            ],
        ),
    ]
