# Generated by Django 2.0 on 2018-09-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_usertransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='transaction_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_rejected_by', to='main_app.SystemUser'),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='transaction_rejected_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='transaction_verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
