# Generated by Django 2.0 on 2018-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_companydetails_mpesa_paybill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='mpesa_paybill_number',
            field=models.CharField(default=1002989, max_length=150),
            preserve_default=False,
        ),
    ]
