# Generated by Django 2.0 on 2018-09-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20180923_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='notify_loan_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='notify_user',
            field=models.BooleanField(default=True),
        ),
    ]
