# Generated by Django 2.0 on 2018-09-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_usertransactions_used_paybill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='loan_interest_percentage',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='number_of_days_to_refund_loan',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='number_of_loan_payment_installments',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemuser',
            name='loan_amount_given_to_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='loan_interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='loan_amount_given_to_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='loan_interest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
