# Generated by Django 2.0 on 2018-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20180928_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='country',
            field=models.CharField(default='Kenya', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetails',
            name='town',
            field=models.CharField(default='Nairobi', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='address',
            field=models.CharField(default='Kilimani', max_length=150),
            preserve_default=False,
        ),
    ]
