# Generated by Django 2.0 on 2018-10-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_slidingadverts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidingadverts',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
