# Generated by Django 2.0 on 2018-10-06 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_ourservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
