# Generated by Django 2.0 on 2018-10-06 16:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20181006_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('short_details', models.CharField(max_length=30)),
                ('description', ckeditor.fields.RichTextField()),
                ('project_image', models.FileField(upload_to='')),
                ('realized', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('added_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SystemUser')),
            ],
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
