# Generated by Django 2.0 on 2018-10-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20181006_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_position', models.CharField(max_length=20)),
                ('testimony', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('added_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('testimonial_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SystemUser')),
            ],
        ),
    ]
