# Generated by Django 2.0 on 2018-10-06 17:54

from django.db import migrations, models
import django.db.models.deletion
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20181006_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='', validators=[main_app.validators.validate_file_extension])),
                ('email', models.EmailField(max_length=50)),
                ('tel1', models.CharField(max_length=20)),
                ('tel2', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('facebook_profile_link', models.URLField(blank=True, null=True)),
                ('linkedin_profile_link', models.URLField(blank=True, null=True)),
                ('twitter_profile_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('added_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_added_by', to='main_app.SystemUser')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_representative', to='main_app.SystemUser')),
            ],
        ),
    ]
