# Generated by Django 2.0 on 2018-10-06 19:16

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_ourpartners'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartners',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ourpartners',
            name='company_logo',
            field=models.FileField(default=1, upload_to='', validators=[main_app.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
