# Generated by Django 2.0 on 2018-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20181006_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourservices',
            name='service_fa_icon_name',
            field=models.CharField(max_length=20),
        ),
    ]
