# Generated by Django 2.0 on 2018-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20181007_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='registered_for_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='tel1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
