# Generated by Django 2.0 on 2018-10-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20181011_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='advertised',
            field=models.BooleanField(default=False),
        ),
    ]
