# Generated by Django 2.0 on 2018-10-11 12:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20181011_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_to_be_filled_on_datetime',
        ),
        migrations.AddField(
            model_name='position',
            name='position_to_be_filled_on_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=50),
        ),
    ]
