# Generated by Django 2.0 on 2018-10-11 12:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20181011_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(max_length=50)),
                ('resource', models.FileField(upload_to='')),
                ('can_be_downloaded', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('added_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('attached_for_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.OurProjects')),
                ('attached_to_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.SystemUser')),
                ('attached_to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Department')),
                ('attached_to_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.OurServices')),
            ],
        ),
    ]
