# Generated by Django 2.0 on 2018-10-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_downloadableresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadableresource',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
