# Generated by Django 2.0 on 2018-10-11 14:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20181011_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadableresource',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='downloadableresource',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='short_details',
            field=models.CharField(max_length=110),
        ),
    ]
