# Generated by Django 2.0 on 2018-10-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20181011_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
