# Generated by Django 2.0 on 2018-10-13 20:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20181013_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourprojects',
            name='clients',
            field=models.CharField(default='Meziz Members', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='project_location',
            field=models.CharField(default='Nairobi, Kenya', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='project_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='main_app.SystemUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='project_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='realization_date',
            field=models.DateField(default=datetime.datetime(2018, 10, 13, 20, 33, 30, 556137, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='show_project_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ourprojects',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_added_by_user', to='main_app.SystemUser'),
        ),
    ]
