# Generated by Django 2.0 on 2018-11-02 12:57

from django.db import migrations, models
import django.db.models.deletion
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_mobileappversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organization', models.CharField(max_length=100)),
                ('organization_physical_address', models.CharField(max_length=100)),
                ('organization_postal_address', models.CharField(max_length=100)),
                ('organization_telephone', models.CharField(max_length=100)),
                ('organization_fax', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_email', models.EmailField(max_length=100)),
                ('organization_category', models.CharField(max_length=100)),
                ('organization_specified_category', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_date_of_registration', models.DateField()),
                ('organization_total_number_of_staff', models.IntegerField()),
                ('how_did_you_know_about_meziz', models.CharField(max_length=100)),
                ('organization_copy_of_registration_certificate', models.FileField(upload_to='', validators=[main_app.validators.validate_file_extension])),
                ('organization_brochure', models.FileField(upload_to='', validators=[main_app.validators.validate_file_extension])),
                ('pre_membership_approved', models.BooleanField(default=False)),
                ('pre_membership_approved_on_date_time', models.DateTimeField(blank=True, null=True)),
                ('mpesa_paybill_number', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_profile_link', models.URLField(blank=True, null=True)),
                ('linkedin_profile_link', models.URLField(blank=True, null=True)),
                ('twitter_profile_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('membership_requested_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('physical_pre_membership_registration_form', models.FileField(blank=True, null=True, upload_to='', validators=[main_app.validators.validate_file_extension])),
                ('pre_membership_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_membership_approved_by', to='main_app.SystemUser')),
            ],
        ),
    ]
