# Generated by Django 2.0 on 2018-11-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_memberorganizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganizations',
            name='request_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberorganizations',
            name='request_viewed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pre_membership_request_viewed_by', to='main_app.SystemUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberorganizations',
            name='request_viewed_on_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
