# Generated by Django 2.0 on 2018-11-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_organizationscategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberorganizations',
            name='organization_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.OrganizationsCategories'),
        ),
    ]
