# Generated by Django 2.0 on 2018-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_auto_20181102_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
