# Generated by Django 2.0 on 2018-11-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_memberorganizations_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='associated_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationscategories',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
