# Generated by Django 2.0 on 2018-11-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0051_auto_20181105_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='associated_file',
            new_name='position_file',
        ),
    ]
