# Generated by Django 2.0 on 2018-11-05 20:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_auto_20181105_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
