# Generated by Django 2.0 on 2018-11-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
