# Generated by Django 2.0 on 2018-12-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_gallery_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('amount_in_account', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('account_added_on_date_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('account_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_approved_by', to='main_app.SystemUser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.OurServices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to='main_app.SystemUser')),
            ],
        ),
    ]
