# Generated by Django 2.0 on 2018-12-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_auto_20181204_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='amount_in_account',
            field=models.IntegerField(default=0),
        ),
    ]
