# Generated by Django 2.0 on 2019-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_auto_20190221_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactions',
            name='intended_date_to_repay_loan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertransactions',
            name='number_of_intended_days_to_repay_loan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
