# Generated by Django 2.0 on 2019-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_auto_20190223_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='profile_image_local_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
