# Generated by Django 2.0 on 2019-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0067_auto_20190225_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrecord',
            name='intended_date_to_repay_loan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
