# Generated by Django 2.0 on 2019-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_loansrecord_intended_date_to_repay_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrecord',
            name='defaulted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loansrecord',
            name='defaulted_for_number_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
