# Generated by Django 2.0 on 2019-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_auto_20190228_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansrecord',
            name='loan_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
